version: '3'

services:

  db:
    image: "postgres:alpine"
    container_name: db
    volumes:
      - queue-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  game-queue-server:
    build: .
    container_name: game-queue-server

    environment:
      FILES_TMP_FOLDERS: ""
      API_PREFIX: https://api.web3.storage
      UPLOAD_ENDPOINT: /upload
      DB_SERVER: db
      POSTGRES_DB: queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MODEL_DETECT_ENDPOINT: detect
      API_TOKEN: your web3 storage api key
    ports:
      - 8082:8082
    links:
      - db
    depends_on:
      - db

volumes:
  queue-data: